os:
  - linux
  - mac

sudo: required

language:
  - node

cache:
  - tests/node_modules/

before-install:
  - npm install -g yarn eslint eslint-config-google

script:
  - eslint view/web/app-jarvis.js
  - echo "checking js format in service ..."
  - yarn ci-lint
  - yarn serve &
