os:
  - linux
  - osx

sudo: required

services:
  - xvfb

language:
  - go
  - python

go:
  - 1.11.x

python:
  - "2.7"

addons:
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver

notifications:
  email: truemac

cache:
  - tests/node_modules/

before-install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - go get -u -v -d ./...
  - cd tests/ && npm install && npm install chromedriver geckodriver && cd ..
  - npm install chromedriver
  - npm install -g http-server selenium-webdriver mocha mochawesome chromedriver geckodriver eslint

script:
  # - cd service && go run maintut.go &
  # - eslint view/web/app-jarvis.js
  # - cd view/web/ && npm start && cd ../..
  # - cd service/ && go test ./... && cd ..
  - ./test-runner.sh
  - xvfb-run -s "-screen 0 1920x1080x16" -a mocha tests/test.js
