os:
  - linux
  - mac

sudo: required

language:
  - node_js

node_js:
  - 12

cache:
  - tests/node_modules/

before-install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install -g yarn eslint eslint-config-google
  - yarn install


script:
  - eslint src/view/web/app-jarvis.js
  - echo "checking js format in service ..."
  - yarn ci-lint
  - yarn serve &
