os:
  -linux

services:
  - xvfb
  - docker

language: go

go:
  - 1.11.x

notifications:
  email: false

cache:
  - tests/node_modules/

before-install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - go get github.com/op/go-logging
  - go get github.com/Harkishen-Singh/Jarvis-personal-assistant/service/utils
  - go get github.com/Harkishen-Singh/Jarvis-personal-assistant/service/controllers
  - cd tests/
  - cd npm install
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.

script:
  - go run service/maintut.go &
  - npm install -g http-server selenium-webdriver mocha mochawesome chromedriver
  - cd view/ && npm start && cd ..
  - go test -v ./...
  - cd tests/
  - npm install
  - xvfb-run -s "-screen 0 1920x1080x16" -a mocha test.js

