os:
  -linux

addons:
  - chrome:stable

services:
  - xvfb
  - docker

language: go

go:
  - 1.11.x

notifications:
  email: false

cache:
  - tests/node_modules

before-install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - go get github.com/op/go-logging
  - go get github.com/Harkishen-Singh/Jarvis-personal-assistant/service/utils
  - go get github.com/Harkishen-Singh/Jarvis-personal-assistant/service/controllers
  - cd tests/
  - cd npm install

script:
  - go run service/maintut.go &
  - npm install -g http-server selenium-webdriver mocha mochawesome
  - cd view/ && npm start && cd ..
  - go test -v ./...
  - cd tests/
  - xvfb-run -s "-screen 0 1920x1080x16" -a mocha tests.js

